### ISSUE TITLE
hello help me

### ISSUE THREAD

**Issue by xp12047** [Warbacon/zunder-zsh#1]
I used your run.sh so that my termux can't access my storage folder, I want to know if it can be uninstalled, please help me  
![Screenshot_20220508_231711_com termux](https://user-images.githubusercontent.com/56335408/167302967-edb7244b-0dc7-4751-8e6c-e3a6a12ae783.jpg)

**Comment by Warbacon** [comment]
Sorry for hearing that. I don't know why that's happening to you, but I just found some bugs in termux, so I'm going to remove it from supported systems until I fix it. Anyway, your error should be fixed if you delete the .zshrc file in the home folder and run chsh -s bash, I should add some instructions to the readme. Thanks for testing Zunder and I'll keep working on it :).

**Comment by Warbacon** [comment]
So I did some research and found that your error is not the script's fault, you should use the cd command to access a folder, e.g. ```cd ~/storage```. Still, exa doesn't seem to work in termux now, at least on my device, so I'm going to remove it from the android install.

**Comment by xp12047** [comment]
>

**Comment by xp12047** [comment]
> 很抱歉听到这个。我不知道为什么会发生这种情况，但我刚刚在 termux 中发现了一些错误，所以我会把它从受支持的系统中删除，直到我知道了。您删除主文件夹中的 .zshrc 错误并运行 chsh -s bash，您应该在自述文件中添加一些说明。感谢测试 Zunder，我会继续努力 :)。

thanks, i will try

**Comment by xp12047** [comment]
> 所以我做了一些研究，发现你的错误不是脚本的错，你应该使用 cd 命令访问一个文件夹，例如`cd ~/storage`. 不过，exa 现在似乎不能在 termux 中工作，至少在我的设备上，所以我打算从 android 安装中删除它。



> 我做了一些研究，发现你的错误不是脚本的，你应该使用 cd 错误设备访问一个文件夹，例如，但是`cd ~/storage`，exa 现在看起来不能在 termux 中工作，至少在我的上，所以我从android 安装中删除它。
Problem solved partly.  It can be accessed using cd, but as I used ~ to access it, it still doesn't work.

**Comment by xp12047** [comment]
> 所以我做了一些研究，发现你的错误不是脚本的错，你应该使用 cd 命令访问一个文件夹，例如`cd ~/storage`. 不过，exa 现在似乎不能在 termux 中工作，至少在我的设备上，所以我打算从 android 安装中删除它。

Problem solved partly.  It can be accessed using cd, but as I used ~ to access it, it still doesn't work.

**Comment by Warbacon** [comment]
Hi again, I just enabled that feature, it should work now. Rerun the script to see the change.

**Comment by xp12047** [comment]
> 您好，我刚刚启用了该功能，现在应该可以使用了。重新运行脚本以查看更改。

marvelous!  It's ready!  Better than the original!  Great work! Thank you really thank you so much 😊🍻, how did you do it?  I want you to teach me where I should supplement this knowledge, I can see from this incident that I really don't understand anything，thankyou！

**Comment by xp12047** [comment]
> 您好，我刚刚启用了该功能，现在应该可以使用了。重新运行脚本以查看更改。
It's really not easy, I must say a few more words to thank you, I searched the Internet for a long time and couldn't find the answer, thank you so much.  You have brought my love of cli back to life, thank you.  Your project is awesome!  Very silky!

**Comment by Warbacon** [comment]
All configuration is in the .zshrc file in the home directory (~/.zshrc). I just put ```setopt autocd``` in there, that enables the feature you requested. You should check out this file if you want to known how everything works, although I need to improve the documentation inside it.

Again, thank you for testing Zunder and for congratulating me 😜.

**Comment by xp12047** [comment]
> 所有配置都在主目录 (~/.zshrc) 中的 .zshrc 文件中。我只是放在`setopt autocd`那里，它启用了您请求的功能。如果你想知道一切是如何工作的，你应该查看这个文件，尽管我需要改进它里面的文档。
> 
> 再次感谢您测试 Zunder 并祝贺我😜.

Thank you 😊

**Comment by xp12047** [comment]
Friends, let me take a look.  The things I installed with node suggest that there are no files, but there are clearly in the folder.  I don't know how to match my path. I have tried bashrc and zshrc, but it doesn't work.  Really anxious.  Please, help me take a look when you have time.  Thanks, I can't find anyone who understands.
![Screenshot_20220513_111342_com termux](https://user-images.githubusercontent.com/56335408/168204574-170b9187-8fff-4a44-87d7-561ee7cee1ea.jpg)
![Screenshot_20220513_111349_com termux](https://user-images.githubusercontent.com/56335408/168204578-c69fa10d-a047-43a1-a395-57933b8f983b.jpg)
![Screenshot_20220513_111400_com termux](https://user-images.githubusercontent.com/56335408/168204581-7504c83f-e176-4321-a1e4-7fa8471d9c51.jpg)
